#Server port
server:
  port: 8888

#Git repo location.
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Komal148/config-server-repo
#          repos:
#            search-paths:
#              - 'track*'
#              - 'user*'
  application:
    name: config-server






